import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {/* Barra de navegação criada para ser compartilhada nas rotas, estilizado com o tailwind */}
        <nav className='flex justify-center gap-4 bg-slate-400'>
          {/* <p>Home</p> */}
          {/* <p>Users</p> */}
          {/* Navegação propagada para todas as rotas */}
          <Link href={"/"} className='hover:text-blue-500'>Home</Link> 
          <Link href={"/users"} className='hover:text-blue-500'>Users</Link> 
          <Link href={"/blog"} className='hover:text-blue-500'>Blog</Link> 
        </nav>
        {children}
      </body>
    </html>
  )
}
