import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//Componente importado para propagar a barra de navegação
import NavBar from './components/NavBar'

//o código foi simplificado
//const Home: NextPage = () => { //componente react
function Home() { // transformado em componente funcional
  console.log("Client Side Rendering?");//Verificar qual lado redenriza - só aparece no lado do cliente
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}
        <NavBar />
        <h1>Página Principal</h1>

      </main>

      
    </div>
  )
}

export default Home
